name: official_extensions
description: Yukino official extensions
version: 0.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  extensions:
    git:
      url: git://github.com/yukino-app/yukino.git
      path: packages/extensions
      ref: redo-architecture

dependency_overrides:
  utilx:
    git:
      url: git://github.com/yukino-app/yukino.git
      path: packages/utilx
      ref: redo-architecture

dev_dependencies:
  lint: ^1.0.0
  path: ^1.8.0
  test: ^1.17.12