name: official_extensions
description: Officially supported extensions of Yukino.
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    extensions:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: extensions
    extensions_dev_tools:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: extensions_dev_tools
    path: ^1.8.0
    utilx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: utilx

dev_dependencies:
    devx:
        git:
            url: git://github.com/yukino-app/packages.git
            ref: devx
    lint: ^1.0.0
