name: Build Extensions

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: dart-lang/setup-dart@v1

            - name: Install dependencies
              run: dart pub get

            - name: Build extensions
              run: dart run ./extensions/repository.dart

            - name: Deploy site
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: dist
                  folder: dist
