name: Test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 * * * *"

env:
    GIT_CONFIG_NAME: "[Automated] Yui"
    GIT_CONFIG_EMAIL: yukino-org@hotmail.com
    GIT_INPUT_DIR: dist/summary
    GIT_OUTPUT_BRANCH: summary

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - uses: dart-lang/setup-dart@v1

            - name: 🚧 Do prerequisites
              run: |
                  dart pub get

            - name: 🧪 Test modules
              run: dart run ./test/all.dart --ci

            - name: 🚀 Upload summary
              working-directory: ${{ env.GIT_INPUT_DIR }}
              run: |
                  git init
                  git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
                  git config --local user.name "${{ env.GIT_CONFIG_NAME }}"
                  git config --local user.email "${{ env.GIT_CONFIG_EMAIL }}"
                  git switch -c ${{ env.GIT_OUTPUT_BRANCH }}
                  git add .
                  git commit --allow-empty -m "[automated] update summary"
                  git push origin -u ${{ env.GIT_OUTPUT_BRANCH }} --force
