name: Test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 * * * *"

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - uses: dart-lang/setup-dart@v1

            - name: 🚧 Do prerequisites
              run: |
                  dart pub get

            - name: 🧪 Test modules
              run: dart run ./test/all.dart --ci

            - name: 🚀 Upload summary
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: dist
                  folder: dist
